spring.application.name=cashflow
server.port=${PORT:8080}

# PostgreSQL Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cashFlow?sslmode=require}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:har6261}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Config
jwt.secret=${JWT_SECRET:O3jdu27xJf8Hs82Dk28F9shd902KJShd9s82JSHd92lKSla9f2HS8d0w9SdfLka92}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Cookie Config (LOCAL)
cookie.secure=false
cookie.same-site=None
cookie.http-only=true

spring.security.oauth2.client.registration.google.client-id=874195631826-5shph85nf2c99i40aq7tg1bonqkn68an.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# Frontend redirect
app.oauth2.redirect-url=http://localhost:8080/dashboard.html

